import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/assets/bulma.scss';
import './globals.scss';

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="has-navbar-fixed-top">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
        <title>moow.cc</title>
      </head>
      <body className={inter.className}>
        <noscript>
          <strong>
            We&apos;re sorry but this doesn&apos;t work properly without JavaScript enabled. Please enable it to
            continue.
          </strong>
        </noscript>
        {/* <Navbar /> */}
        <Navbar />

        {/* Main Content */}
        <main className="main-content"> {children} </main>

        <Footer />
      </body>
    </html>
  );
}